name: uvenv
base: core24
adopt-info: version
summary: Command-line tool for virtual environment management
description: A simple command-line tool for managing virtual environments written in Rust.

grade: stable
confinement: strict

apps:
  uvenv:
    command: usr/bin/uvenv
    extensions: []
    plugs:
      - network

parts:
  version:
    plugin: nil
    source: https://github.com/robinvandernoord/uvenv.git
    source-type: git
    build-packages:
      - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags `git rev-list --tags --max-count=1`)"

  link-app:
    # build happens outside of snapcraft, this step turns binary into snap.
    plugin: dump
    source: target/release
    override-build: |
      set -eu
      install -D ./uv $SNAPCRAFT_PART_INSTALL/usr/bin/uv
      install -D ./uvenv $SNAPCRAFT_PART_INSTALL/usr/bin/uvenv

